<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>RuinaCoop</AssemblyName>
    <RootNamespace>RuinaCoop</RootNamespace>
    <GameDir Condition="'$(GameDir)' == ''">D:\game\steamapps\common\Library Of Ruina</GameDir>
    <ManagedDir>$(GameDir)\LibraryOfRuina_Data\Managed</ManagedDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>$(ManagedDir)\Facepunch.Steamworks.Win64.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ManagedDir)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>    <PackageReference Include="HarmonyX" Version="2.9.0" />
  </ItemGroup>
</Project>